version: '3.8'

services:
  loja-web:
    build: .
    container_name: technova-store
    ports:
      - "5000:5000"
    volumes:
 
      - ./data.json:/app/data.json
    environment:
      - FLASK_DEBUG=1
    restart: unless-stopped